In [15]:
import pandas as pd
import numpy as np

df = pd.read_csv('~/Documents/datamining/project/census-data0/ACS_16_5YR_S1903.csv', encoding="latin-1", skiprows=1)
df

,Id,Id2,Geography,Total; Estimate; Households,Total; Margin of Error; Households,Median income (dollars); Estimate; Households,Median income (dollars); Margin of Error; Households,Total; Estimate; Households - One race-- - Some other race,Total; Margin of Error; Households - One race-- - Some other race,Median income (dollars); Estimate; Households - One race-- - Some other race,...,Median income (dollars); Estimate; NONFAMILY HOUSEHOLDS - Nonfamily households - Male householder,Median income (dollars); Margin of Error; NONFAMILY HOUSEHOLDS - Nonfamily households - Male householder,Total; Estimate; NONFAMILY HOUSEHOLDS - Nonfamily households - Male householder - Living alone,Total; Margin of Error; NONFAMILY HOUSEHOLDS - Nonfamily households - Male householder - Living alone,Median income (dollars); Estimate; NONFAMILY HOUSEHOLDS - Nonfamily households - Male householder - Living alone,Median income (dollars); Margin of Error; NONFAMILY HOUSEHOLDS - Nonfamily households - Male householder - Living alone,Total; Estimate; NONFAMILY HOUSEHOLDS - Nonfamily households - Male householder - Not living alone,Total; Margin of Error; NONFAMILY HOUSEHOLDS - Nonfamily households - Male householder - Not living alone,Median income (dollars); Estimate; NONFAMILY HOUSEHOLDS - Nonfamily households - Male householder - Not living alone,Median income (dollars); Margin of Error; NONFAMILY HOUSEHOLDS - Nonfamily households - Male householder - Not living alone
0,310M300US10180,10180,"Abilene, TX Metro Area",60308,718,46473,1571,5.1,0.6,36415.0,...,31214,2381,37.0,2.4,26356,2262,11.6,1.8,44464,7329
1,310M300US10380,10380,"Aguadilla-Isabela, PR Metro Area",110149,1329,15564,450,15.2,0.7,15252.0,...,10196,799,38.3,1.5,9576,629,6.7,0.8,15152,2780
2,310M300US10420,10420,"Akron, OH Metro Area",283472,1265,51749,519,0.2,0.1,41250.0,...,36208,1031,37.4,0.8,31876,787,9.9,0.6,55151,3635
3,310M300US10500,10500,"Albany, GA Metro Area",57795,837,38674,1173,0.5,0.2,42720.0,...,30389,2092,38.4,2.2,28146,3009,7.0,1.3,41166,9891
4,310M300US10540,10540,"Albany, OR Metro Area",45378,551,46782,1603,1.0,0.3,55455.0,...,30414,2795,34.5,2.5,25884,1548,11.7,2.2,44264,2949
5,310M300US10580,10580,"Albany-Schenectady-Troy, NY Metro Area",345957,1652,63758,626,1.0,0.1,42819.0,...,43690,1651,35.4,0.7,39028,1453,11.0,0.5,69479,3997
6,310M300US10740,10740,"Albuquerque, NM Metro Area",343268,1780,49711,763,11.1,0.4,36165.0,...,35051,1411,37.2,0.9,30619,1092,9.9,0.6,57145,5334
7,310M300US10780,10780,"Alexandria, LA Metro Area",55440,682,41836,1303,0.2,0.1,54479.0,...,30249,2348,38.8,2.4,27910,3334,7.4,1.2,40509,7178
8,310M300US10900,10900,"Allentown-Bethlehem-Easton, PA-NJ Metro Area",315449,1411,60441,592,3.4,0.2,38289.0,...,42607,1464,35.7,0.9,37283,1599,11.0,0.6,67401,2528
9,310M300US11020,11020,"Altoona, PA Metro Area",50954,438,44033,1187,0.2,0.1,NaN,...,30118,2349,36.5,1.7,25988,2367,8.1,1.4,45382,4261
10,310M300US11100,11100,"Amarillo, TX Metro Area",95689,836,51672,940,2.1,0.3,42115.0,...,34560,2355,37.4,1.8,31889,1340,9.9,1.3,50820,6230
11,310M300US11180,11180,"Ames, IA Metro Area",36544,380,51201,1342,0.4,0.2,18646.0,...,27488,3447,27.7,2.0,29070,5265,24.8,1.9,26563,4047
12,310M300US11260,11260,"Anchorage, AK Metro Area",135808,982,79225,1180,1.4,0.2,54318.0,...,56003,4121,40.8,1.4,46426,3458,13.6,1.0,87569,6473
13,310M300US11460,11460,"Ann Arbor, MI Metro Area",138672,804,62484,984,0.6,0.1,30346.0,...,40571,1452,31.8,1.0,35636,1783,16.1,0.9,48844,3114
14,310M300US11500,11500,"Anniston-Oxford-Jacksonville, AL Metro Area",45071,581,41954,1381,0.8,0.3,31223.0,...,30908,2851,37.4,2.3,27756,4763,8.5,1.8,39159,2843
15,310M300US11540,11540,"Appleton, WI Metro Area",90033,660,61840,808,1.2,0.2,38026.0,...,42016,2068,37.7,1.6,37033,2237,11.8,1.2,59622,6887
16,310M300US11640,11640,"Arecibo, PR Metro Area",67049,833,17069,567,9.0,0.8,15648.0,...,10435,837,36.6,2.3,9618,782,4.2,1.0,22375,8377
17,310M300US11700,11700,"Asheville, NC Metro Area",183799,1278,46443,899,0.7,0.1,40921.0,...,30118,1287,33.0,1.1,26986,1275,8.6,0.7,51411,4170
18,310M300US12020,12020,"Athens-Clarke County, GA Metro Area",73260,710,40955,1240,1.3,0.3,30966.0,...,25110,2102,29.7,1.7,22687,2092,14.9,1.6,33084,5694
19,310M300US12060,12060,"Atlanta-Sandy Springs-Roswell, GA Metro Area",1994730,5460,59183,301,2.3,0.1,38679.0,...,44515,827,35.5,0.4,39944,870,10.2,0.3,66624,1531
20,310M300US12100,12100,"Atlantic City-Hammonton, NJ Metro Area",101083,982,55456,1308,4.3,0.4,42603.0,...,36315,1839,35.5,1.5,30703,2883,9.0,1.1,60508,6173
21,310M300US12220,12220,"Auburn-Opelika, AL Metro Area",57901,751,45056,1961,0.8,0.3,55032.0,...,26104,4107,36.3,2.3,27974,5421,15.1,1.7,23869,2550
22,310M300US12260,12260,"Augusta-Richmond County, GA-SC Metro Area",211238,1699,47178,821,1.1,0.2,29638.0,...,34229,2550,37.9,1.3,30514,2057,7.1,0.7,50419,3389
23,310M300US12420,12420,"Austin-Round Rock, TX Metro Area",706066,2531,66093,508,3.7,0.1,43259.0,...,50063,1062,35.2,0.6,42134,867,14.5,0.5,68884,2004
24,310M300US12540,12540,"Bakersfield, CA Metro Area",262337,1275,49788,909,9.4,0.4,42409.0,...,39128,3201,40.1,1.5,34386,2842,11.1,0.9,55545,4046
25,310M300US12580,12580,"Baltimore-Columbia-Towson, MD Metro Area",1040674,3214,72801,505,0.9,0.1,59874.0,...,51879,785,33.7,0.5,44140,1487,10.3,0.3,85866,3838
26,310M300US12620,12620,"Bangor, ME Metro Area",61787,619,45302,1150,0.1,0.1,46875.0,...,28216,2039,32.1,2.1,23059,1987,12.2,1.7,48194,2991
27,310M300US12700,12700,"Barnstable Town, MA Metro Area",94351,1125,65382,1119,0.7,0.2,45197.0,...,43589,2166,33.0,1.4,35848,2099,8.2,1.0,81986,5871
28,310M300US12940,12940,"Baton Rouge, LA Metro Area",301189,1828,53004,853,0.6,0.1,42130.0,...,39454,1491,37.3,1.3,37300,1368,10.9,0.7,50752,4039
29,310M300US12980,12980,"Battle Creek, MI Metro Area",53089,569,44681,1179,0.3,0.1,39688.0,...,31922,1616,40.2,2.0,29592,2659,7.6,1.3,50223,7926
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359,310M300US46520,46520,"Urban Honolulu, HI Metro Area",309548,1361,77161,727,0.8,0.1,48866.0,...,52908,1519,37.5,1.0,46010,1504,11.6,0.7,82027,6536
360,310M300US46540,46540,"Utica-Rome, NY Metro Area",115930,872,49580,1121,0.8,0.2,25708.0,...,32543,1668,37.2,1.2,29536,1396,9.0,0.9,56270,4172
361,310M300US46660,46660,"Valdosta, GA Metro Area",51447,639,37793,1084,1.6,0.4,30365.0,...,25799,2497,36.8,2.2,22923,4048,12.1,1.6,29980,5798
362,310M300US46700,46700,"Vallejo-Fairfield, CA Metro Area",145315,947,69227,1596,6.2,0.4,57675.0,...,50420,2431,33.0,1.4,45047,3232,12.3,1.1,71783,8091
363,310M300US47020,47020,"Victoria, TX Metro Area",35311,565,54671,2471,3.9,0.5,40676.0,...,45283,4227,38.4,3.3,38723,5045,9.3,2.4,55541,4871
364,310M300US47220,47220,"Vineland-Bridgeton, NJ Metro Area",50718,751,49537,1599,7.4,0.9,38061.0,...,33107,4331,33.4,2.6,26762,3380,11.4,2.0,56528,8115
365,310M300US47260,47260,"Virginia Beach-Norfolk-Newport News, VA-NC Met...",636750,2415,60059,405,1.1,0.1,44465.0,...,46161,796,35.3,0.7,41478,701,11.2,0.5,65595,1863
366,310M300US47300,47300,"Visalia-Porterville, CA Metro Area",134153,756,42789,1042,9.4,0.6,37584.0,...,32146,2236,36.8,1.9,26765,2814,12.5,1.4,46496,3939
367,310M300US47380,47380,"Waco, TX Metro Area",92632,927,43778,1402,3.2,0.4,35996.0,...,25835,1834,35.6,2.1,22455,1889,10.5,1.5,40875,5078
368,310M300US47460,47460,"Walla Walla, WA Metro Area",23540,450,48015,2111,4.4,0.8,49474.0,...,31211,2846,34.1,2.8,27544,4004,7.3,1.7,58365,19347
369,310M300US47580,47580,"Warner Robins, GA Metro Area",67983,899,52400,1675,1.5,0.3,36038.0,...,40513,2200,38.7,2.7,40000,3875,8.4,2.0,53654,17368
370,310M300US47900,47900,"Washington-Arlington-Alexandria, DC-VA-MD-WV M...",2155967,4751,93804,405,3.6,0.1,59929.0,...,73596,978,33.5,0.3,63069,743,11.2,0.3,110383,2460
371,310M300US47940,47940,"Waterloo-Cedar Falls, IA Metro Area",67011,531,52469,1061,0.7,0.2,64292.0,...,39276,4110,35.4,1.5,34089,1832,12.8,1.2,61287,10270
372,310M300US48060,48060,"Watertown-Fort Drum, NY Metro Area",43428,603,49911,1403,0.9,0.3,41627.0,...,35515,3173,40.4,2.1,30839,2721,9.3,1.6,49815,13981
373,310M300US48140,48140,"Wausau, WI Metro Area",54003,544,54227,1236,0.1,0.1,24107.0,...,35860,1487,38.0,2.1,32084,1555,10.6,1.4,60746,8329
374,310M300US48260,48260,"Weirton-Steubenville, WV-OH Metro Area",50554,541,42319,1129,0.1,0.1,32045.0,...,31889,2385,36.3,2.1,28783,1786,8.0,1.2,57740,17246
375,310M300US48300,48300,"Wenatchee, WA Metro Area",41548,631,52475,1600,6.3,0.6,41130.0,...,37015,3283,37.1,2.9,32146,3561,9.2,2.3,54446,7980
376,310M300US48540,48540,"Wheeling, WV-OH Metro Area",59557,603,43736,1288,0.1,0.1,NaN,...,27366,1695,37.9,1.5,24916,1964,7.6,1.1,39815,12235
377,310M300US48620,48620,"Wichita, KS Metro Area",243758,1123,52068,651,1.4,0.2,40319.0,...,33734,1332,41.9,1.0,31282,931,7.4,0.6,51742,3953
378,310M300US48660,48660,"Wichita Falls, TX Metro Area",56052,780,46043,1226,2.2,0.4,23788.0,...,35184,2896,36.5,1.9,31394,1921,8.3,1.3,49737,8429
379,310M300US48700,48700,"Williamsport, PA Metro Area",45587,608,48731,1150,0.2,0.1,19148.0,...,34992,2260,38.0,2.2,31495,1241,9.6,1.4,56863,9466
380,310M300US48900,48900,"Wilmington, NC Metro Area",110133,991,50445,919,1.0,0.2,29137.0,...,37487,2823,32.3,1.3,32336,2715,11.3,0.9,56186,4079
381,310M300US49020,49020,"Winchester, VA-WV Metro Area",50487,609,56053,1410,0.7,0.3,36087.0,...,35141,2424,41.5,2.3,32096,1270,8.7,1.5,70965,8825
382,310M300US49180,49180,"Winston-Salem, NC Metro Area",259085,1415,45296,696,1.3,0.2,31971.0,...,31813,1065,36.0,1.0,28967,2008,8.2,0.7,47355,3067
383,310M300US49340,49340,"Worcester, MA-CT Metro Area",347055,1409,65973,883,2.5,0.2,34638.0,...,43286,1823,35.6,0.8,36310,1174,11.3,0.7,69331,2402
384,310M300US49420,49420,"Yakima, WA Metro Area",80196,710,45700,933,10.0,0.7,38693.0,...,32041,2384,36.7,2.2,28904,2818,10.8,1.6,40724,5787
385,310M300US49620,49620,"York-Hanover, PA Metro Area",168008,941,59853,817,1.0,0.2,26893.0,...,42157,1519,36.1,1.0,36201,1999,11.5,1.0,66226,3901
386,310M300US49660,49660,"Youngstown-Warren-Boardman, OH-PA Metro Area",229342,1222,43455,528,0.2,0.1,35640.0,...,30729,734,38.5,0.8,28115,1308,7.4,0.6,48307,4588
387,310M300US49700,49700,"Yuba City, CA Metro Area",57683,548,51008,1383,5.2,0.6,41609.0,...,34466,5366,35.8,2.4,27407,2784,14.4,1.9,55385,7875
388,310M300US49740,49740,"Yuma, AZ Metro Area",70924,952,41467,1093,16.9,1.0,38112.0,...,31890,2882,39.1,2.4,26365,2410,12.8,1.6,60794,10865

In [22]:
arr = {"Boston", "New York", "Philadelphia", "Chicago", "Cleveland-", "Detroit", "Indianapolis", "Milwaukee", "Atlanta", "Charlotte-", "Miami", "Orlando", "Washington", "Denver", "Minneapolis", "Oklahoma", "Portland-Vancouver", "Salt Lake", "Oakland", "Los Angeles", "Phoenix", "Sacramento", "Dallas", "Houston", "Memphis", "New Orleans", "San Antonio"}
df1 = df[["Geography", "Total; Estimate; Households", "Median income (dollars); Estimate; Households"]]
df1

,Geography,Total; Estimate; Households,Median income (dollars); Estimate; Households
0,"Abilene, TX Metro Area",60308,46473
1,"Aguadilla-Isabela, PR Metro Area",110149,15564
2,"Akron, OH Metro Area",283472,51749
3,"Albany, GA Metro Area",57795,38674
4,"Albany, OR Metro Area",45378,46782
5,"Albany-Schenectady-Troy, NY Metro Area",345957,63758
6,"Albuquerque, NM Metro Area",343268,49711
7,"Alexandria, LA Metro Area",55440,41836
8,"Allentown-Bethlehem-Easton, PA-NJ Metro Area",315449,60441
9,"Altoona, PA Metro Area",50954,44033
10,"Amarillo, TX Metro Area",95689,51672
11,"Ames, IA Metro Area",36544,51201
12,"Anchorage, AK Metro Area",135808,79225
13,"Ann Arbor, MI Metro Area",138672,62484
14,"Anniston-Oxford-Jacksonville, AL Metro Area",45071,41954
15,"Appleton, WI Metro Area",90033,61840
16,"Arecibo, PR Metro Area",67049,17069
17,"Asheville, NC Metro Area",183799,46443
18,"Athens-Clarke County, GA Metro Area",73260,40955
19,"Atlanta-Sandy Springs-Roswell, GA Metro Area",1994730,59183
20,"Atlantic City-Hammonton, NJ Metro Area",101083,55456
21,"Auburn-Opelika, AL Metro Area",57901,45056
22,"Augusta-Richmond County, GA-SC Metro Area",211238,47178
23,"Austin-Round Rock, TX Metro Area",706066,66093
24,"Bakersfield, CA Metro Area",262337,49788
25,"Baltimore-Columbia-Towson, MD Metro Area",1040674,72801
26,"Bangor, ME Metro Area",61787,45302
27,"Barnstable Town, MA Metro Area",94351,65382
28,"Baton Rouge, LA Metro Area",301189,53004
29,"Battle Creek, MI Metro Area",53089,44681
...,...,...,...
359,"Urban Honolulu, HI Metro Area",309548,77161
360,"Utica-Rome, NY Metro Area",115930,49580
361,"Valdosta, GA Metro Area",51447,37793
362,"Vallejo-Fairfield, CA Metro Area",145315,69227
363,"Victoria, TX Metro Area",35311,54671
364,"Vineland-Bridgeton, NJ Metro Area",50718,49537
365,"Virginia Beach-Norfolk-Newport News, VA-NC Met...",636750,60059
366,"Visalia-Porterville, CA Metro Area",134153,42789
367,"Waco, TX Metro Area",92632,43778
368,"Walla Walla, WA Metro Area",23540,48015
369,"Warner Robins, GA Metro Area",67983,52400
370,"Washington-Arlington-Alexandria, DC-VA-MD-WV M...",2155967,93804
371,"Waterloo-Cedar Falls, IA Metro Area",67011,52469
372,"Watertown-Fort Drum, NY Metro Area",43428,49911
373,"Wausau, WI Metro Area",54003,54227
374,"Weirton-Steubenville, WV-OH Metro Area",50554,42319
375,"Wenatchee, WA Metro Area",41548,52475
376,"Wheeling, WV-OH Metro Area",59557,43736
377,"Wichita, KS Metro Area",243758,52068
378,"Wichita Falls, TX Metro Area",56052,46043
379,"Williamsport, PA Metro Area",45587,48731
380,"Wilmington, NC Metro Area",110133,50445
381,"Winchester, VA-WV Metro Area",50487,56053
382,"Winston-Salem, NC Metro Area",259085,45296
383,"Worcester, MA-CT Metro Area",347055,65973
384,"Yakima, WA Metro Area",80196,45700
385,"York-Hanover, PA Metro Area",168008,59853
386,"Youngstown-Warren-Boardman, OH-PA Metro Area",229342,43455
387,"Yuba City, CA Metro Area",57683,51008
388,"Yuma, AZ Metro Area",70924,41467

In [17]:
#alternate method of parsing the data, not working

#for column in df1:
#    temp = (df1['Geography'])
#    print(temp)
#    for city in arr:
#        print(city)
#        if city in temp:
#            print(df1.loc[column])
#            df2.append(df1.loc[column])
#
#df1[5]
#df2

In [24]:
df2 = pd.DataFrame(index=range(3))
df3 = pd.DataFrame(index=range(3))
cntr = 1

for city in arr:
    if cntr is 1:
        df3 = df1[df1['Geography'].str.contains(city)]
        cntr = cntr + 1
    else:
        df2 = df1[df1['Geography'].str.contains(city)]
        df3 = df3.append(df2)

df3

,Geography,Total; Estimate; Households,Median income (dollars); Estimate; Households
70,"Chicago-Naperville-Elgin, IL-IN-WI Metro Area",3464942,63327
44,"Boston-Cambridge-Newton, MA-NH Metro Area",1784448,77809
253,"New York-Newark-Jersey City, NY-NJ-PA Metro Area",7138559,69211
162,"Houston-The Woodlands-Sugar Land, TX Metro Area",2223829,60902
234,"Minneapolis-St. Paul-Bloomington, MN-WI Metro ...",1343140,70915
66,"Charlotte-Concord-Gastonia, NC-SC Metro Area",885916,55191
229,"Miami-Fort Lauderdale-West Palm Beach, FL Metr...",2065161,50064
281,"Portland-Vancouver-Hillsboro, OR-WA Metro Area",896514,62772
213,"Los Angeles-Long Beach-Anaheim, CA Metro Area",4298857,62216
75,"Cleveland-Elyria, OH Metro Area",848772,51001
97,"Denver-Aurora-Lakewood, CO Metro Area",1058467,68173
166,"Indianapolis-Carmel-Anderson, IN Metro Area",749799,54261
273,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD Me...",2235205,63952
252,"New Orleans-Metairie, LA Metro Area",479206,48319
302,"Sacramento--Roseville--Arden-Arcade, CA Metro ...",804137,61686
274,"Phoenix-Mesa-Scottsdale, AZ Metro Area",1596641,55227
261,"Oklahoma City, OK Metro Area",500437,52825
233,"Milwaukee-Waukesha-West Allis, WI Metro Area",626504,55625
311,"Salt Lake City, UT Metro Area",375127,64564
264,"Orlando-Kissimmee-Sanford, FL Metro Area",816428,50183
315,"San Francisco-Oakland-Hayward, CA Metro Area",1674040,85947
227,"Memphis, TN-MS-AR Metro Area",495558,48545
88,"Dallas-Fort Worth-Arlington, TX Metro Area",2451163,61330
99,"Detroit-Warren-Dearborn, MI Metro Area",1672081,54037
19,"Atlanta-Sandy Springs-Roswell, GA Metro Area",1994730,59183
370,"Washington-Arlington-Alexandria, DC-VA-MD-WV M...",2155967,93804
313,"San Antonio-New Braunfels, TX Metro Area",786156,54638